server:
  port: 8083
  servlet:
    context-path: /product-catalog

spring:
  application:
    name: catalog-service

  data:
    mongodb:
      database: ${env.MONGO_DATABASE}
      uri: mongodb+srv://${env.MONGO_USER}:${env.MONGO_PASSWORD}@${env.MONGO_CLUSTER}
    redis:
      url: ${env.REDIS_URL:redis://localhost:6379}
    cache:
      type: redis

app:
  cache-prefix: "product-catalog:"